# Generated by Django 5.1.2 on 2024-11-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50, verbose_name='Mebel turini tanlang')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Mebel nomi')),
                ('summary', models.CharField(blank=True, max_length=450, null=True, verbose_name="Mebel haqida qisqacha ta'rif")),
                ('body', models.TextField(verbose_name="mebel haqida batafsil ma'lumot")),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Mebel rasmi')),
                ('material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mebelda ishlatilgan material')),
                ('price', models.CharField(max_length=50, verbose_name='Mebelni sotilish narxi')),
                ('rek_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mebel reklama narxi')),
            ],
        ),
    ]
