# Generated by Django 5.1.2 on 2024-11-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebel',
            name='categoty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newsapp.category', verbose_name='Mebel turini tanlang'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=50, verbose_name='Mebel turini kiriting'),
        ),
    ]
