# Generated by Django 5.1.2 on 2024-11-09 18:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_mebel_categoty_alter_category_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebel',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name="Mebel haqida batafsil ma'lumot"),
        ),
    ]
